# Generated by Django 3.1.5 on 2021-01-25 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='video',
            field=models.FileField(default='', upload_to='media/video/%Y-%m-%d'),
            preserve_default=False,
        ),
    ]
