# Generated by Django 3.1.5 on 2021-01-25 07:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0002_video_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='dis_like',
            field=models.ManyToManyField(blank=True, related_name='dis_likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='video',
            name='like',
            field=models.ManyToManyField(blank=True, related_name='likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
