# Generated by Django 3.1.5 on 2021-01-25 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210125_1630'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='hit_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='video',
            name='video',
            field=models.FileField(upload_to='video/%Y-%m-%d'),
        ),
    ]
