# Generated by Django 3.1.5 on 2021-01-26 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210125_1746'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Follow',
        ),
    ]
